### PR TITLE
[WIP] Add Workflow and Testsuite

### PR DESCRIPTION
**Pull request by Heiss**
Current Status: Work in Progress

This PR implements a github workflow to publish this module to pypi, when tests success. This tests generates a coverage file, too and will be pushed to [codeclimate](https://codeclimate.com/login/github/join), which is free for OSS.

This workflow needs tokens in settings, which needs @odwdinc to login to (it would be okay for me to do this, but then i need developer rights for this project).

The name of tokens needs to be:
- [pypi](https://pypi.org/): pypi_password
- [codeclimate](https://codeclimate.com/login/github/join): CodeClimate

Status:

- [x] Workflows
  - [x] publish on PYPI, when tests success
  - [x] CodeClimate for code coverage
- [ ] Testsuite with meaningful tests (with [mock](https://docs.python.org/3/library/unittest.mock.html))
- [ ] add convenience
  - [x] [pipenv](https://pypi.org/project/pipenv/) for pipfile (tracking and lock version of dependencies, python environments)
  - [x] better naming for usage (PythonSimConnect is redundant, because it is a python module)
  - [ ] pythonic names for methods
  - [x] Makefile for easier executions within workflow and CLI
  - [x] add logging module instead of print for better usability and CLI friendly (you can configure logger, what you want to see)
  - [x] restructure folder for separating source and tests
  - [x] add setup.py for easier installations (`python setup.py install` for installation within git folder)
  - [x] add more ignores in gitignore :)

My thoughts about tests: I would [mock](https://docs.python.org/3/library/unittest.mock.html) the connection to the SimConnect.dll away, but i do not know the response of requests to SimConnect.dll.

### CODE REVIEW

**Comment by odwdinc** [comment]
@Heiss wow, thank you very much!
I have added you as a collaborator.

**Comment by Heiss** [comment]
@odwdinc  Ahhhh. I am not finished... :D

But you need to set the tokens in settings! Otherwise the workflow will not working. Or i need a greater permission, because as a collaborator i cannot set the tokens... Also i could create a codespace (i am in the beta since today).

**Comment by Heiss** [comment]
But you need to set the tokens in settings! Otherwise the workflow will not working. Or i need a greater permission, because as a collaborator i cannot set the tokens...

**Comment by Heiss** [comment]
@odwdinc  Can you reopen this PR? Or do i need to open a new one?

**Comment by odwdinc** [comment]
No sorry, I looks like i messed up there.

**Comment by Heiss** [comment]
@odwdinc 
No problem. I will create a new one with same description, when i update :) Meanwhile, you can try to give me rights for token or set up them by yourself. :)

**Comment by odwdinc** [comment]
did i do it? https://pypi.org/project/SimConnect/
not 100% how to do the CodeClimate one.

**Pull request merged**
