### PR TITLE
Add COM and NAV frequency change buttons

### PR DESCRIPTION
**Pull request by jhanford**
Added new COM1, COM2, NAV1 and NAV2 frequency change buttons to the Autopilot screen
Added a new method - triggerSimEventNoAlert - to perform the change but not show a visual feedback on the web page, so as to aid quick changing of frequencies

### CODE REVIEW

**Comment by hankhank10** [comment]
Thank you for contribution to this.

I have a couple of questions.

First - and excuse my ignorance of aviation - but are setting the NAV and COM frequencies relevant for the autopilot? Or would they be better under a radios tab?

Second, with regard to the "no alert" trigger would it make more sense to have one function which includes an option for alert / no alert (defaulting to alert)?

Thanks again! This is a great addition!

**Comment by jhanford** [comment]
Here's some answers:

First - Yep, you're totally right. It should be with the radios tab, sorry. I added it quickly last night since COM and NAV setting in the game is my biggest pain point. Far too fiddly with the mouse.

Second - Yeah, I was thinking of modding the existing method, but thought it would be clearer to have the separate one, but you're right, overloading the existing method makes more sense.

**Comment by odwdinc** [comment]
all looks good form my end, thanks for this!
@hankhank10 look good to you?

**Comment by hankhank10** [comment]
Superb work @jhanford

Agree, let's merge it in

**Pull request merged**
