### PR TITLE
Moving back to CDN

### PR DESCRIPTION
**Pull request by hankhank10**
Looks like it was a mistake to move to local hosting of the bootstrap js/css as it overwhelms the local server.

Better to get them from the remote CDN - particularly as most users will likely have them already cached.

### CODE REVIEW

**Comment by odwdinc** [comment]
ahh much stable, ?? on press button getting
image

**Comment by hankhank10** [comment]
That shouldn't be happening. Will review and re-pull.

**Comment by hankhank10** [comment]
I can't replicate. Can you check that isn't from old cached JS by doing a hard reload on the page in incognito mode?

**Comment by odwdinc** [comment]
Yah it was on my end, sorry was from old cached JS :(

**Comment by hankhank10** [comment]
Cool. I've been building all of this front end JS on the dummy server today. Will connect up to the sim this evening and do a proper test through everything to make sure it actually works.

Overall I'm pretty happy with how it is all shaping up, feels like it's heading towards an actually useful app. Once I've tested everything I'm going to try to find a few users away from us willing to do some testing. In particular I'm keen to understand how all this going on impacts performance of the game.

**Pull request merged**
