### PR TITLE
Add support for Camera variables

### LINKED ISSUE #124: Is it possible to get CAMERA_STATE etc?
I have MSFS running, I can get a whole bunch of aircraft information using `qa.get("SOME_SIM_VAR_NAME")`, but the `CAMERA_STATE` var, and other camera-related values, are all `None` rather than the enums they're supposed to return.

### PR DESCRIPTION
**Pull request by Pomax**
Added all variables listed on https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Camera_Variables.htm

Fixes https://github.com/odwdinc/Python-SimConnect/issues/124

### CODE REVIEW

**Comment by Pomax** [comment]
@odwdinc merry christmas, and a happy new year =)

would it be possible to merge this in?

**Comment by AntCant** [comment]
Thanks **@Pomax**! Desperately needed the camera state, this works great!

**Comment by Pomax** [comment]
Cheers. You may want to have a look at https://github.com/odwdinc/Python-SimConnect/pull/127 too in this case, as I've been adding support for more variables as I run into them being missing (since I'm writing an MSFS demonstrator autopilot in python atm) so if and until the various PRs are merged in, you may want to add `git+https://github.com/pomax/python-simconnect@master#egg=simconnect` to your requirements.txt (or, of course, a specific commit rather than master)

**Comment by Pomax** [comment]
superceded by https://github.com/odwdinc/Python-SimConnect/pull/127

**Pull request closed without merging**
