### PR TITLE
[WIP] Add Workflow and Testsuite

### PR DESCRIPTION
**Pull request by Heiss**
# Current Status: **Work in Progress**

This PR implements a github workflow to publish this module to pypi, when tests success. This tests generates a coverage file, too and will be pushed to [codeclimate](https://codeclimate.com/login/github/join), which is free for OSS.

This workflow needs tokens in settings, which needs @odwdinc to login to (it would be okay for me to do this, but then i need developer rights for this project).

The name of tokens needs to be:
- [pypi](https://pypi.org/): pypi_password
- [codeclimate](https://codeclimate.com/login/github/join): CodeClimate

Status:

- [x] Workflows
  - [x] publish on PYPI, when tests success
  - [x] CodeClimate for code coverage
- [x] create entities to make it easier to work with
  - [x] Plane (Altitude, Longitude etc.)
  - [x] Tests for plane entity
  - [x] create a trigger / event / measurements entity to make it easier to configure the requested informations.
- [x] add convenience
  - [x] [pipenv](https://pypi.org/project/pipenv/) for pipfile (tracking and lock version of dependencies, python environments)
  - [x] better naming for usage (PythonSimConnect is redundant, because it is a python module)
  - [x] pythonic names for public methods
  - [x] Makefile for easier executions within workflow and CLI
  - [x] add logging module instead of print for better usability and CLI friendly (you can configure logger, what you want to see)
  - [x] restructure folder for separating source and tests
  - [x] add setup.py for easier installations (`python setup.py install` for installation within git folder)
  - [x] add more ignores in gitignore :)
  - [x] add pypi badge to readme
- [ ] add asyncio and cache for values to make it easier for users to work with SimConnect (if there is no value retrieved from SimConnect, return a cached value)

My thoughts about tests: I would [mock](https://docs.python.org/3/library/unittest.mock.html) the connection to the `SimConnect.dll` away, but i do not know the response of requests to SimConnect.dll. Here i can use any help.

More informations:
@odwdinc If you want to publish a new version of this module, you have to increment the value here
https://github.com/odwdinc/Python-SimConnect/blob/2825b4451f6318fbea235a9f854ad7123a50a05c/SimConnect/__init__.py#L10

Otherwise you will get errors in pypi publishing, which is not a problem, because you do not want to publish every commit to master on pypi. This is easier to maintain and is a better solution, because you can fix errors without publish the errors to pypi.

### CODE REVIEW

**Comment by Heiss** [comment]
@odwdinc Ah. I found the draft option. :) Ups. This had fixed our misscommunication 👯

**Comment by odwdinc** [comment]
so i test the pip install, all seem to work well, How is best to handle the SimConnect.dll, I see it needs to be in the same dir as the script or you can pass library_path to SimConnect, right? any thoughts there?

**Comment by Heiss** [comment]
> so i test the pip install, all seem to work well, How is best to handle the SimConnect.dll, I see it needs to be in the same dir as the script or you can pass library_path to SimConnect, right? any thoughts there?

I think it is not a good idea to distribute the SimConnect.dll via pypi, because it is copyrighted of microsoft and their property. So it could be a bad idea (i would remove it from git, too).

You can set library_path to your SimConnect.dll, yes. We should write a tutorial into the README.md to show, how you get this dll from the official servers of microsoft. This is inconvenient, but this is the safest way. Also, we should look at other library around SimConnect and see, how they solved this problem.

**Comment by Heiss** [comment]
We need a cache for values and make the get_data calls asynchroneous, so we get a better performance (and easier usage).
But i do not understand your code in detail... i think there is a cache already. This could i use for async calls.

**Comment by odwdinc** [comment]
> We need a cache for values and make the get_data calls asynchroneous, so we get a better performance (and easier usage).
> But i do not understand your code in detail... i think there is a cache already. This could i use for async calls.

sData is not needed it was just fun to get object names working, lets just remove sData and output dic by default.
`_format=True `path.

`self.out_data[_Request.DATA_REQUEST_ID]`
holds the data if there is been any received on the last call to `self.__CallDispatch`

**Comment by CallMeRafiki** [comment]
> I think it is not a good idea to distribute the SimConnect.dll via pypi, because it is copyrighted of microsoft and their property. So it could be a bad idea (i would remove it from git, too).
> 
> You can set library_path to your SimConnect.dll, yes. We should write a tutorial into the README.md to show, how you get this dll from the official servers of microsoft. This is inconvenient, but this is the safest way. Also, we should look at other library around SimConnect and see, how they solved this problem.

Agreed with not distributing the SimConnect.dll. However, instead of writing a tutorial for getting the dll from official Microsoft servers, why not just include in README.md where to get it from the MSFS SDK? When downloading the SDK it downloads the SimConnect.dll automatically (See below for example of where the dll was downloaded for me). The SDK can be installed directly from inside MSFS itself. The only real advantage of this over having people download it from the official Microsoft servers is that it keeps focus on the game versus focusing users on what I see as "outside/external" sources.

 `C:\MSFS SDK\SimConnect SDK\lib\SimConnect.dll`

**Comment by Heiss** [comment]
Sorry, i do not found the time recently to work on this. Also the module make some great improvements.  So i need more time to rewrite some parts of my PR. I hope i can find the time in the next few days.

**Comment by Heiss** [comment]
@CallMeRafiki 
> > I think it is not a good idea to distribute the SimConnect.dll via pypi, because it is copyrighted of microsoft and their property. So it could be a bad idea (i would remove it from git, too).
> > You can set library_path to your SimConnect.dll, yes. We should write a tutorial into the README.md to show, how you get this dll from the official servers of microsoft. This is inconvenient, but this is the safest way. Also, we should look at other library around SimConnect and see, how they solved this problem.
> 
> Agreed with not distributing the SimConnect.dll. However, instead of writing a tutorial for getting the dll from official Microsoft servers, why not just include in README.md where to get it from the MSFS SDK? When downloading the SDK it downloads the SimConnect.dll automatically (See below for example of where the dll was downloaded for me). The SDK can be installed directly from inside MSFS itself. The only real advantage of this over having people download it from the official Microsoft servers is that it keeps focus on the game versus focusing users on what I see as "outside/external" sources.
> 
> `C:\MSFS SDK\SimConnect SDK\lib\SimConnect.dll`

This was discussed also in the issue #23 and it seems, that other projects includes the dll aswell. So we should keep it that way currently.

**Pull request closed without merging**
